const About = () => {
    return (
        <div>
            <h1>About</h1>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Doloremque aperiam nobis inventore recusandae est maxime minus! Laborum libero voluptate accusantium odit perferendis voluptatibus velit iure eaque, tenetur et necessitatibus accusamus, maxime fugit blanditiis ullam ducimus molestiae non distinctio nulla placeat ipsa commodi cumque enim. Laborum distinctio recusandae dolores? Nobis, quam harum ipsa ut optio illum sequi corrupti? Ab natus praesentium expedita dignissimos culpa cumque suscipit quas dolorum nulla? Ipsum, exercitationem minima laborum beatae aspernatur dignissimos quas aperiam sapiente!</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Doloremque aperiam nobis inventore recusandae est maxime minus! Laborum libero voluptate accusantium odit perferendis voluptatibus velit iure eaque, tenetur et necessitatibus accusamus, maxime fugit blanditiis ullam ducimus molestiae non distinctio nulla placeat ipsa commodi cumque enim. Laborum distinctio recusandae dolores? Nobis, quam harum ipsa ut optio illum sequi corrupti? Ab natus praesentium expedita dignissimos culpa cumque suscipit quas dolorum nulla? Ipsum, exercitationem minima laborum beatae aspernatur dignissimos quas aperiam sapiente!</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Doloremque aperiam nobis inventore recusandae est maxime minus! Laborum libero voluptate accusantium odit perferendis voluptatibus velit iure eaque, tenetur et necessitatibus accusamus, maxime fugit blanditiis ullam ducimus molestiae non distinctio nulla placeat ipsa commodi cumque enim. Laborum distinctio recusandae dolores? Nobis, quam harum ipsa ut optio illum sequi corrupti? Ab natus praesentium expedita dignissimos culpa cumque suscipit quas dolorum nulla? Ipsum, exercitationem minima laborum beatae aspernatur dignissimos quas aperiam sapiente!</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Doloremque aperiam nobis inventore recusandae est maxime minus! Laborum libero voluptate accusantium odit perferendis voluptatibus velit iure eaque, tenetur et necessitatibus accusamus, maxime fugit blanditiis ullam ducimus molestiae non distinctio nulla placeat ipsa commodi cumque enim. Laborum distinctio recusandae dolores? Nobis, quam harum ipsa ut optio illum sequi corrupti? Ab natus praesentium expedita dignissimos culpa cumque suscipit quas dolorum nulla? Ipsum, exercitationem minima laborum beatae aspernatur dignissimos quas aperiam sapiente!</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Doloremque aperiam nobis inventore recusandae est maxime minus! Laborum libero voluptate accusantium odit perferendis voluptatibus velit iure eaque, tenetur et necessitatibus accusamus, maxime fugit blanditiis ullam ducimus molestiae non distinctio nulla placeat ipsa commodi cumque enim. Laborum distinctio recusandae dolores? Nobis, quam harum ipsa ut optio illum sequi corrupti? Ab natus praesentium expedita dignissimos culpa cumque suscipit quas dolorum nulla? Ipsum, exercitationem minima laborum beatae aspernatur dignissimos quas aperiam sapiente!</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Doloremque aperiam nobis inventore recusandae est maxime minus! Laborum libero voluptate accusantium odit perferendis voluptatibus velit iure eaque, tenetur et necessitatibus accusamus, maxime fugit blanditiis ullam ducimus molestiae non distinctio nulla placeat ipsa commodi cumque enim. Laborum distinctio recusandae dolores? Nobis, quam harum ipsa ut optio illum sequi corrupti? Ab natus praesentium expedita dignissimos culpa cumque suscipit quas dolorum nulla? Ipsum, exercitationem minima laborum beatae aspernatur dignissimos quas aperiam sapiente!</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Doloremque aperiam nobis inventore recusandae est maxime minus! Laborum libero voluptate accusantium odit perferendis voluptatibus velit iure eaque, tenetur et necessitatibus accusamus, maxime fugit blanditiis ullam ducimus molestiae non distinctio nulla placeat ipsa commodi cumque enim. Laborum distinctio recusandae dolores? Nobis, quam harum ipsa ut optio illum sequi corrupti? Ab natus praesentium expedita dignissimos culpa cumque suscipit quas dolorum nulla? Ipsum, exercitationem minima laborum beatae aspernatur dignissimos quas aperiam sapiente!</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Doloremque aperiam nobis inventore recusandae est maxime minus! Laborum libero voluptate accusantium odit perferendis voluptatibus velit iure eaque, tenetur et necessitatibus accusamus, maxime fugit blanditiis ullam ducimus molestiae non distinctio nulla placeat ipsa commodi cumque enim. Laborum distinctio recusandae dolores? Nobis, quam harum ipsa ut optio illum sequi corrupti? Ab natus praesentium expedita dignissimos culpa cumque suscipit quas dolorum nulla? Ipsum, exercitationem minima laborum beatae aspernatur dignissimos quas aperiam sapiente!</p>
        </div>
     );
}

export default About;
